#!/bin/sh

DHCP_DEFAULT_DUID=$(fw_printenv -n dhcp_default_duid 2>/dev/null)

# Set defaults if the value is missing
DHCP_DEFAULT_DUID=${DHCP_DEFAULT_DUID:-"000000000000000000000000000000000000"}

uci -q batch << EOI

set network.globals.ula_prefix='fd08::/48'
set network.globals.packet_steering='0'
set network.globals.dhcp_default_duid='$DHCP_DEFAULT_DUID'

set network.lan.ipaddr='192.168.8.1'
set network.lan.netmask='255.255.255.0'
set network.lan.multipath='off'

set network.wan.hostname='*'

commit network
EOI

exit 0
