#!/bin/sh

# This script sets the root password hash in /etc/shadow based on the value stored in U-Boot environment variable 'root_password_hash'.
# A password can be added to U-Boot using the following commands:
#
# First, generate the password hash using openssl:
# ># openssl passwd -5 "your_password"
#
# Then set the resulting hash in U-Boot:
# ># fw_setenv root_password_hash 'your_generated_hash'
#
# Do not use double quotes when setting the hash in U-Boot, as it may cause issues because it can interpret $ from the hash string as bash variable.

ROOT_HASH=$(fw_printenv -n root_password_hash 2>/dev/null)

[ -z "$ROOT_HASH" ] && exit 0

sed -i "s|^root:[^:]*:|root:$ROOT_HASH:|" /etc/shadow

exit 0
